env:
  global:
    - CC_TEST_REPORTER_ID=dd8476ca37cd711ef9c8b40c5b7faa6d1ea1fcf61163af83a9259ceaa5ce77ac
language: node_js
node_js: 
  - stable

services :
  - postgresql

postgres:
  adapter: postgresql
  database: DB_DATABASE_URL
  username: postgres

install:
  - npm install
before_script:
  - psql -c 'create DATABASE fastfoodfast;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

cache:
  directories:
  - "node_modules"

script:
  - npm test

after_success: 
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT